name: Petpy CI
run-name: Continuous Integration
on: [push]
jobs:
  build-and-test:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04, macos-13]
        python: [3.8.10, 3.9.13, 3.10.11, 3.11.9, 3.12.3, 3.13.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Validate version
        run: |
          $pythonVersion = (python --version)
          if ("Python ${{ matrix.python }}" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python }}"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: python/install-packages
        run: |
          pip install -r test-requirements.txt
          python setup.py install

      - name: Run Tests
        run: |
          cd tests/ 
          pytest
          cd ../

      - name: Codecov
        run: |
          codecov -t $CODECOV_TOKEN

      - name: Coveralls
        run: |
          cd tests/
          coverage run --source=petpy -m pytest
          cd ../
          coveralls