name: Petpy CI
run-name: Continuous Integration
on: [push]
jobs:
  build-and-test:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, ubuntu-22.04]
        python: [3.11.9, 3.12.3, 3.13.0]
        exclude:
          - os: ubuntu-22.04
            python: 3.8.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Validate version
        run: |
          $pythonVersion = (python --version)
          if ("Python ${{ matrix.python }}" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python }}"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: python/install-packages
        run: |
          pip install -r test-requirements.txt
          python setup.py install

      - name: Run Tests
        env:
          PETPY_PETFINDER_KEY: ${{ secrets.PETPY_PETFINDER_KEY }}
          PETPY_PETFINDER_SECRET_KEY: ${{ secrets.PETPY_PETFINDER_SECRET_KEY }}
        run: |
          echo $PETPY_PETFINDER_KEY
          echo $PETPY_PETFINDER_SECRET_KEY
          pytest

      - name: Codecov
        run: |
          codecov -t $CODECOV_TOKEN

      - name: Coveralls
        env:
          PETPY_PETFINDER_KEY: ${{ secrets.PETPY_PETFINDER_KEY }}
          PETPY_PETFINDER_SECRET_KEY: ${{ secrets.PETPY_PETFINDER_SECRET_KEY }}
        run: |
          coverage run --source=petpy -m pytest
          coveralls